// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_board_cpp();
RcppExport SEXP _rcpp_module_boot_camel_cpp();
RcppExport SEXP _rcpp_module_boot_die_cpp();
RcppExport SEXP _rcpp_module_boot_game_cpp();
RcppExport SEXP _rcpp_module_boot_legbet_cpp();
RcppExport SEXP _rcpp_module_boot_player_cpp();
RcppExport SEXP _rcpp_module_boot_simulator_cpp();
RcppExport SEXP _rcpp_module_boot_space_cpp();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_board_cpp", (DL_FUNC) &_rcpp_module_boot_board_cpp, 0},
    {"_rcpp_module_boot_camel_cpp", (DL_FUNC) &_rcpp_module_boot_camel_cpp, 0},
    {"_rcpp_module_boot_die_cpp", (DL_FUNC) &_rcpp_module_boot_die_cpp, 0},
    {"_rcpp_module_boot_game_cpp", (DL_FUNC) &_rcpp_module_boot_game_cpp, 0},
    {"_rcpp_module_boot_legbet_cpp", (DL_FUNC) &_rcpp_module_boot_legbet_cpp, 0},
    {"_rcpp_module_boot_player_cpp", (DL_FUNC) &_rcpp_module_boot_player_cpp, 0},
    {"_rcpp_module_boot_simulator_cpp", (DL_FUNC) &_rcpp_module_boot_simulator_cpp, 0},
    {"_rcpp_module_boot_space_cpp", (DL_FUNC) &_rcpp_module_boot_space_cpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_CamelUp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
