# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Board
#' @title Encapsulates a double
#' @description Type the name of the class to see its methods
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Paramter: other - The other Double object
#' \item Returns: product of the values
#' }
#' @export
NULL

#' @name Camel
#' @title Encapsulates a double
#' @description Type the name of the class to see its methods
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Paramter: other - The other Double object
#' \item Returns: product of the values
#' }
#' @export
NULL

#' @name Die
#' @title Encapsulates a double
#' @description Type the name of the class to see its
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Paramter: other - The other Double object
#' \item Returns: product of the values
#' }
#' @export
#'
NULL

#' @name Game
#' @title Encapsulates a double
#' @description Type the name of the class to see its methods
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Paramter: other - The other Double object
#' \item Returns: product of the values
#' }
#' @export
NULL

#' @name LegBet
#' @title Encapsulates a double
#' @description Type the name of the class to see its methods
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Paramter: other - The other Double object
#' \item Returns: product of the values
#' }
#' @export
NULL

#' @name Player
#' @title Encapsulates a double
#' @description Type the name of the class to see its
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Paramter: other - The other Double object
#' \item Returns: product of the values
#' }
#' @export
#'
NULL

#' @name Simulator
#' @title Encapsulates a double
#' @description Type the name of the class to see its methods
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Paramter: other - The other Double object
#' \item Returns: product of the values
#' }
#' @export
NULL

#' @name Space
#' @title Encapsulates a double
#' @description Type the name of the class to see its methods
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Paramter: other - The other Double object
#' \item Returns: product of the values
#' }
#' @export
NULL

